# Generated by Django 4.2.5 on 2023-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='firstname',
        ),
        migrations.AddField(
            model_name='login',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='other',
            field=models.ImageField(default='', upload_to='post'),
        ),
        migrations.AlterField(
            model_name='students',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
