# Generated by Django 4.2.5 on 2023-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0002_remove_login_firstname_login_first_name_post_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
